// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/mittwald/go-powerdns"
)

// ClientOption is an autogenerated mock type for the ClientOption type
type ClientOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: c
func (_m *ClientOption) Execute(c *pdns.Client) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*pdns.Client) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
