// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	servers "github.com/mittwald/go-powerdns/apis/servers"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetServer provides a mock function with given fields: ctx, serverID
func (_m *Client) GetServer(ctx context.Context, serverID string) (*servers.Server, error) {
	ret := _m.Called(ctx, serverID)

	var r0 *servers.Server
	if rf, ok := ret.Get(0).(func(context.Context, string) *servers.Server); ok {
		r0 = rf(ctx, serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servers.Server)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListServers provides a mock function with given fields: ctx
func (_m *Client) ListServers(ctx context.Context) ([]servers.Server, error) {
	ret := _m.Called(ctx)

	var r0 []servers.Server
	if rf, ok := ret.Get(0).(func(context.Context) []servers.Server); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]servers.Server)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
