// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	search "github.com/mittwald/go-powerdns/apis/search"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx, serverID, query, max, objectType
func (_m *Client) Search(ctx context.Context, serverID string, query string, max int, objectType search.ObjectType) (search.ResultList, error) {
	ret := _m.Called(ctx, serverID, query, max, objectType)

	var r0 search.ResultList
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, search.ObjectType) search.ResultList); ok {
		r0 = rf(ctx, serverID, query, max, objectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(search.ResultList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, search.ObjectType) error); ok {
		r1 = rf(ctx, serverID, query, max, objectType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
