// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ClientAuthenticator is an autogenerated mock type for the ClientAuthenticator type
type ClientAuthenticator struct {
	mock.Mock
}

// OnConnect provides a mock function with given fields: _a0
func (_m *ClientAuthenticator) OnConnect(_a0 *http.Client) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Client) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRequest provides a mock function with given fields: _a0
func (_m *ClientAuthenticator) OnRequest(_a0 *http.Request) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Request) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
