// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	cache "github.com/mittwald/go-powerdns/apis/cache"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Flush provides a mock function with given fields: ctx, serverID, name
func (_m *Client) Flush(ctx context.Context, serverID string, name string) (*cache.FlushResult, error) {
	ret := _m.Called(ctx, serverID, name)

	var r0 *cache.FlushResult
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *cache.FlushResult); ok {
		r0 = rf(ctx, serverID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cache.FlushResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, serverID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
